# Generated by Django 4.2.6 on 2023-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('cpf', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('income', models.FloatField()),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
